### ISSUE TITLE
Error read project.json

### ISSUE THREAD

**Issue by andyoknen** [olback/rdg-linux#23]
Hey. I can't read project.json - could only get to this place

https://github.com/olback/rdg-linux/blob/24d8841c76ae282cc1a6b4c4098749ad069ab401/src/lib/cJSON.c#L1025

(process:23220): GLib-GIO-CRITICAL **: 03:53:28.527: g_input_stream_read: assertion 'G_IS_INPUT_STREAM (stream)' failed
Error parsing json

**Comment by olback** [comment]
That's weird..  
Looks like a bug in the gtk library maybe?
GLib fails to read the resource and just warns and continues, as a result of that the parsing fails since parsing `NULL` is rather pointless.

What are the steps to reproduce the issue? When I run `make run` it just works without error.
I know there have been issues on ElementaryOS before but I don't know if it's still broken. 

What distro and version are you using?
